### ISSUE TITLE
Tagging for latest

### ISSUE THREAD

**Issue by sasezaki** [koriym/Koriym.QueryLocator#6]
Could you tagging for latest master as `1.3.1` ?
I need [delete composer.phar · koriym/Koriym.QueryLocator@337200d](https://github.com/koriym/Koriym.QueryLocator/commit/337200d242a1e76272449509efa52c6b998afca2) to shut up IDE(PHPStorm) warning.
<img width="410" alt="phpstorm_notice_outputinterface" src="https://user-images.githubusercontent.com/42755/50431566-1e5bc180-090f-11e9-8cc3-36ae97488d0c.png">
<img width="924" alt="phpstorm_notice_outputinterface2" src="https://user-images.githubusercontent.com/42755/50431567-1f8cee80-090f-11e9-8604-ba38f13a4d3a.png">

**Comment by koriym** [comment]
Thanks, will be tagged soon after some cleanup.

**Comment by koriym** [comment]
Thanks for the reporting. Tagged 1.3.1 !

**Comment by sasezaki** [comment]
thanks!
